######################################################################
# Automatically generated by qmake (2.01a) Fr. Aug 15 13:35:47 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES +=

OTHER_FILES += \
    fastBrushlessControl.ino

HEADERS += \
    motorControl.h
